### ISSUE TITLE
Transform exercises in Stack projects

### ISSUE THREAD

**Issue by rbasso** [exercism/xhaskell#185]
##### Tracking migration of exercises to Stack projects

This issue is just for tracking. If you are interested in the discussion, please see #182.

###### Phase 1 - Preparing a proof-of-concept

- [ ] Change `.gitignore` to stop ignoring `stack.yaml` and `packages.yaml`.
- [ ] Change `.travis.yml` to support exercises that are already Stack projects.
- [ ] Migrate exercise `pov` to a Stack project.
- [ ] Add a stub solution to `pov`.

###### Phase 2 - Online-testing the proof-of-concept

- [ ] Check if fetching works as expected.
- [ ] Check if everything builds locally without problems.
- [ ] Check if submitting works as expected.

###### Phase 3 - Creating the transitional documentation

- [ ] Rewrite `docs/INSTALLATION.md`.
- [ ] Rewrite `docs/TESTS.md`.
- [ ] Rewrite `README.md`.
- [ ] Rewrite `SETUP.md`.

###### Phase 4 - Migrating all exercises

- [ ] pov
- [ ] lens-person
- [ ] forth
- [ ] zipper
- [ ] go-counting
- [ ] sgf-parsing
- [ ] parallel-letter-frequency
- [ ] connect
- [ ] simple-cipher
- [ ] sieve
- [ ] series
- [ ] secret-handshake
- [ ] say
- [ ] saddle-points
- [ ] pythagorean-triplet
- [ ] pig-latin
- [ ] pascals-triangle
- [ ] palindrome-products
- [ ] nth-prime
- [ ] custom-set
- [ ] linked-list
- [ ] food-chain
- [ ] wordy
- [ ] trinary
- [ ] octal
- [ ] ocr-numbers
- [ ] minesweeper
- [ ] house
- [ ] matrix
- [ ] clock
- [ ] luhn
- [ ] largest-series-product
- [ ] hexadecimal
- [ ] difference-of-squares
- [ ] binary-search-tree
- [ ] queen-attack
- [ ] robot-simulator
- [ ] kindergarten-garden
- [ ] crypto-square
- [ ] bank-account
- [ ] all-your-base
- [ ] atbash-cipher
- [ ] allergies
- [ ] raindrops
- [ ] prime-factors
- [ ] binary
- [ ] roman-numerals
- [ ] scrabble-score
- [ ] triangle
- [ ] beer-song
- [ ] meetup
- [ ] robot-name
- [ ] etl
- [ ] word-count
- [ ] list-ops
- [ ] simple-linked-list
- [ ] grade-school
- [ ] nucleotide-count
- [ ] phone-number
- [ ] anagram
- [ ] space-age
- [ ] hamming
- [ ] strain
- [ ] sum-of-multiples
- [ ] bob
- [ ] gigasecond
- [ ] grains
- [ ] sublist
- [ ] rna-transcription
- [ ] accumulate
- [ ] leap

###### Phase 5 - Creating the final documentation

- [ ] Rewrite `docs/INSTALLATION.md`.
- [ ] Rewrite `docs/TESTS.md`.
- [ ] Rewrite `README.md`.
- [ ] Rewrite `SETUP.md`.

###### Phase 6 - Cleaning up

- [ ] Rewrite `.travis.yml`.
- [ ] Remove `_test` and update `config.json`.
- [ ] Remove `Vagrantfile`.

###### Phase 7 - Updating the resolver

- [ ] Update `.travis.yml` to test match the latest working snapshot.
- [ ] Update `exercises/*/stack.yaml` to the same snapshot.
