### ISSUE TITLE
discussion: Making the Haskell track more idiomatic

### ISSUE THREAD

**Issue by rbasso** [exercism/xhaskell#194]
###### Making the Haskell track more idiomatic

With #115 we started to review some exercises to make them feel more like Haskell. As a result, we did the following:

- Changed the return type of `rna-transcription` to a `Maybe`
- Changed the return type of `phone-number` to an `Either String`
- Changed the return type of `nucleotide-count` to a `Maybe`

There are many other unidiomatic things that can appear in the track:

- Single letters represented as *Strings*.
- Using *Int* when *Integer* makes more sense.
- Use *Integer* when any *Integral* can be used.
- Partial functions instead of returning *Maybe*.
- Requiring lists when any *Foldable* is possible.
- ...

This doesn't means that we should change everything that is not idiomatic, because sometimes unidiomatic code can be easier for beginners. But we should not allow it when it it not clear that it is the case.

###### List of unidiomatic things in the track we could fix

- [x] ~~`grains` is not a total function. Could return a *Maybe*. (#197)~~
- [x] ~~`hamming` is not defined for unequal lists. Could return a *Maybe*. (#199)~~
- [x] ~~`etl` uses *String* to represent a single letter. Should use *Char*. (#198)~~
- [ ] `roman-numerals` could return a *Maybe*.
- [ ] `crypto-square` returns a matrix as a String, with spaces representing row breaks and missing elements. (#259)

###### List of things we could do to promote idiomatic programming

- [x] ~~`strain`: change tests to enforce lazy processing of the lists. (#194)~~

##### Anyone knows of any specific thing that could/should be changed to make this track more idiomatic?

**Comment by rbasso** [comment]
User's comment about `simple-linked-list`:

> Ok. Maybe in Ruby or other OO brain damaged languages it's fun.
> But why do I need to reinvent Prelude here? Dumbest task ever.

**Comment by rbasso** [comment]
Should `roman-numerals` return a *Maybe* or *Either* if *n > 3000* or *n < 1*?

**Comment by petertseng** [comment]
I would find `Maybe String` good.

Note that if truly desired, 3999 could be allowed.

**Comment by rbasso** [comment]
> Note that if truly desired, 3999 could be allowed.

Makes perfect sense. :smile: 
We should also change `3000` to `3999` in `x-common`.

**Comment by rbasso** [comment]
Considering that is issue is open for a while and that we have opened issues to deal with all the agreed changes, I'm closing this PR now, so that we can focus on the more practical issues.

If anyone opposes, I will reopen it immediately.
