### ISSUE TITLE
tests: Tracking migration to hspec with fail-fast.

### ISSUE THREAD

**Issue by rbasso** [exercism/xhaskell#211]
##### Tracking migration to `hspec` with *fail-fast*

This issue is just for tracking. If you are interested in the discussion, please see #190.

##### Preparing

- [x] ~~Create branch `hspec-fail-fast`~~

##### Migrating all exercises

- Completely rewrite the test to use `hspec` with *fail-fast*.
- Update test cases to match `x-common`, if needed.
- Update `package.yaml`.
- Merge PR to ~~`hspec-fail-fast`~~ `master`

###### Exercises

- [x] leap
- [x] accumulate
- [x] sublist
- [x] grains
- [x] gigasecond
- [x] bob
- [x] sum-of-multiples
- [x] strain
- [x] hamming
- [x] rna-transcription
- [x] space-age
- [x] anagram
- [x] phone-number
- [x] nucleotide-count
- [x] grade-school
- [x] simple-linked-list
- [x] list-ops
- [x] word-count
- [x] etl
- [x] robot-name
- [x] meetup
- [x] beer-song
- [x] triangle
- [x] scrabble-score
- [x] roman-numerals
- [x] binary
- [x] prime-factors
- [x] raindrops
- [x] allergies
- [x] atbash-cipher
- [x] all-your-base
- [x] bank-account
- [x] crypto-square
- [x] kindergarten-garden
- [x] robot-simulator
- [x] queen-attack
- [x] binary-search-tree
- [x] difference-of-squares
- [x] hexadecimal
- [x] largest-series-product
- [x] luhn
- [x] clock
- [x] matrix
- [x] house
- [x] minesweeper
- [x] ocr-numbers
- [x] octal
- [x] trinary
- [x] wordy
- [x] food-chain
- [x] linked-list
- [x] custom-set
- [x] nth-prime
- [x] palindrome-products
- [x] pascals-triangle
- [x] pig-latin
- [x] pythagorean-triplet
- [x] saddle-points
- [x] say
- [x] secret-handshake
- [x] series
- [x] sieve
- [x] simple-cipher
- [x] connect
- [x] parallel-letter-frequency
- [x] sgf-parsing
- [x] go-counting
- [x] zipper
- [x] forth
- [x] lens-person
- [x] pov

##### Testing

- [X] ~~Clear *Travis-CI* cache.~~
- [X] ~~Check if build and rebuild times are reasonable.~~

##### Merging and cleaning up

- [X] ~~Merge `hspec-fail-fast` on `master`.~~
- [X] ~~Delete branch `hspec-fail-fast`.~~
- [x] Clear *Travis-CI* cache and rebuild.

This accidentally fixes #263.
Closes #190.

**Comment by rbasso** [comment]
After 65 days and 71 PRs, we finally finished rewriting all exercises to use `hspec`.
Now every test suite will automatically stop on the first fail.

It's time to celebrate, @petertseng! :tada: :tropical_drink: :dancer:  :confetti_ball: :beers:
