### ISSUE TITLE
Move hints from test suites and stub solutions to HINTS.md

### ISSUE THREAD

**Issue by rbasso** [exercism/xhaskell#302]
Currently we have some exercises with hints as comments in the test suite and/or in the stub solution.

Hints in the stub solutions are convenient - users are almost forced to read them - but proved to be a mess, because most users submit the code with the comments.

Hints in the test suite are not that bad, but they force the users to inspect it. I think that, ideally, users should get feedback running the tests, not studying them.

Anyway, considering that the contents of `HINTS.md` is automatically included in the `README.md`, it is the perfect place for hints. We just need to make it happen!

All the exercises that already have a `HINTS.md` file share the same formatting,

```markdown
## Hints

```

so we are using this as a standard for now.

~~This issue will track the migration's progress as soon as we have a complete list of exercises to be changed.~~

#### Tracking changes

- [x] allergies #324
- [x] bank-account #325
- [x] binary-search-tree #329 
- [x] clock #330
- [x] custom-set #331
- [x] forth #343
- [x] go-counting #344
- [x] grade-school #332
- [x] lens-person #381 (comments removed when ported to `hspec`)
- [x] linked-list #333
- [x] matrix #334
- [x] meetup #335 
- [x] octal #383
- [X] ~~pov (nothing to fix)~~
- [x] queen-attack #336 
- [x] rna-transcription #382 (comments removed)
- [x] robot-name #337
- [x] robot-simulator #338 
- [x] sgf-parsing #300 (fixed when ported to `hspec`)
- [x] simple-linked-list #339
- [x] space-age #340 
- [x] sublist #341 
- [x] trinary #384
- [x] wordy #342 
- [x] zipper #385 (comments removed when ported to `hspec`)

**Comment by rbasso** [comment]
Hints' migration to `HINTS.md` files finished. :smile:
