### ISSUE TITLE
Remove compatibility code.

### ISSUE THREAD

**Issue by rbasso** [exercism/xhaskell#303]
Since we merged #282, there is no need for us to keep any kind of compatibility code in this track. This allows us to remove some lines from a few exercises and make the code a little more clear and beautiful.

~~This issue will track the cleaning progress as soon as we have a complete list of files to be changed.~~

#### Tracking changes

- [x] all-your-base #307 
- [x] bank-account #308 
- [x] binary-search-tree #309 
- [x] forth #310 
- [x] gigasecond #311 
- [x] hamming #312 
- [x] largest-series-product #313 
- [x] linked-list #314 
- [x] list-ops #315 
- [x] matrix #316 
- [x] raindrops #317 
- [x] robot-name #318 
- [x] saddle-points #319 
- [x] say #320 
- [x] sum-of-multiples #321 
- [x] word-count #322 
- [x] wordy #323

**Comment by rbasso** [comment]
Considering that we removed all the compatibility code we could find until now (17 exercises), I'm closing this issue now.

If later we discover that we missed something, we can just open additional PRs and mention this issue.
