### ISSUE TITLE
hlint: Improve existing code based on suggestions

### ISSUE THREAD

**Issue by rbasso** [exercism/xhaskell#355]
To promote good coding practices, we are changing `README.md` to recommend contributors to run `HLint` before every submission. #354

That may help in the future, but running `hlint` on `master` indicates that there is also a lot of work to be done right now. The following is a list of files to inspect and decide if we should accept *HLint*'s suggestions:

- [X] `allergies/src/Example.hs` #356 
- [X] `all-your-base/src/Example.hs` #357 
- [X] `all-your-base/test/Tests.hs` #357 
- [x] `bank-account/test/Tests.hs` #379
- [x] `binary-search-tree/test/Tests.hs` #375 
- [X] `bob/src/Example.hs` #358 
- [X] `clock/test/Tests.hs` #359
- [X] `custom-set/src/Example.hs` #360 
- [X] `custom-set/test/Tests.hs` #360 
- [X] `forth/src/Example.hs` #361 
- [X] `forth/test/Tests.hs` #361 
- [X] `go-counting/src/Counting.hs` #362 
- [X] `go-counting/src/Example.hs` #362 
- [X] `hamming/src/Example.hs` #363 
- [x] `hexadecimal/src/Example.hs` #376 (one hint ignored)
- [x] `linked-list/test/Tests.hs` #377 (three hints ignored)
- [X] `list-ops/src/Example.hs` #370, #373 (one hint ignored)
- [X] `matrix/test/Tests.hs` #364 
- [X] `minesweeper/src/Example.hs` #365 
- [x] `ocr-numbers/src/Example.hs` #378 
- [X] `pascals-triangle/test/Tests.hs` #366 
- [X] `pig-latin/src/Example.hs` #367 
- [X] `pig-latin/test/Tests.hs` #367 
- [x] `pov/src/Example.hs` #371
- [x] `pov/test/Tests.hs` #371 
- [X] `raindrops/src/Example.hs` #369 
- [x] `robot-name/src/Example.hs` #380 
- [x] `robot-name/test/Tests.hs` #380 
- [X] `simple-cipher/src/Example.hs` #372 
- [X] `simple-linked-list/src/Example.hs` #368

**Comment by petertseng** [comment]
When this is all said and done perhaps we should consider adding it to travis. On a quick look... it seems a bit strange that there is a *parse error* on `robot-name/src/Example.hs` ...?!

**Comment by petertseng** [comment]
We may also consider whether we want to make everything required if we put it in Travis. It looks like hlint has various levels (suggestion, warning, error)

**Comment by rbasso** [comment]
>  there is a parse error on robot-name/src/Example.hs

I saw that, but I didn't inspect it carefully.

> When this is all said and done perhaps we should consider adding it to travis...
>
> We may also consider whether we want to make everything required if we put it in Travis. It looks like hlint has various levels (suggestion, warning, error).

Depending on how we can fine tine the suggestions, that would be great. Sometimes it gives suggestion I would like to ignore...

ps: My plan was to finish the PRs today, but I'll have to leave it for tomorrow.

**Comment by petertseng** [comment]
> On a quick look... it seems a bit strange that there is a *parse error* on `robot-name/src/Example.hs`

We are not alone, I suppose. https://github.com/ndmitchell/hlint/issues/216

**Comment by rbasso** [comment]
`list-ops` is huge a problem for our plan of running it in Travis...

**Comment by petertseng** [comment]
> `list-ops` is a huge problem for our plan of running `hlint` in Travis...

Will telling hlint to ignore it be an acceptable solution? As we might see in http://community.haskell.org/~ndm/darcs/hlint/hlint.htm

I added a `{-# ANN foldr "HLint: ignore Use foldr" #-}` and it ignored that particular warning

**Comment by rbasso** [comment]
Great finding! :+1: 

> Will telling hlint to ignore it be an acceptable solution?

Even if we don't run `hlint` in Travis, it seems a good idea! :smile:

**Comment by rbasso** [comment]
With the ability to suppress specific HLint's suggestion, I believe we'll be able to run it in Travis.

First we have to keep changing and supressing unwanted suggestions until we get no hints.

Later, we'll have to find a way to install it in Travis. I didn't look at at, but I bet this will be the hardest part.

**Comment by petertseng** [comment]
> Later, we'll have to find a way to install it in Travis. I didn't look at at, but I bet this will be the hardest part.

Surprisingly (?), this appears not to be so hard:

https://github.com/petertseng/xhaskell/commit/6682e7475f3c167c10bde2d70dbd1db656f19932

resulting in:

https://travis-ci.org/petertseng/xhaskell/jobs/162545955

**Comment by petertseng** [comment]
Curiosity - this appears to have installed a different version than what I have locally. You see that I got it from the apt repos. The Travis workers run Precise, don't they... http://packages.ubuntu.com/source/precise/hlint seems to say that would be 1.8.24, whereas the version I have installed locally is 1.9.37. The suggestions given are different (on Travis, there is a `liftM` suggestion that I don't have locally, and the `pattern` parse error is missing).

So it may be better to have stack install a later version. Hopefully that is not *that* much harder...?

**Comment by rbasso** [comment]
> Hopefully that is not that much harder

A little. Another problem is that it may increase initial building times.

**Comment by petertseng** [comment]
> Another problem is that it may increase initial building times. 

Oh, you are right, this adds almost 8 minutes to the build time

https://travis-ci.org/petertseng/xhaskell/jobs/162546960

**Comment by rbasso** [comment]
8 minutes?!

I'll run some more tests later, but I'm still optimistic about it. :)

**Comment by rbasso** [comment]
I guess we are done with fixing all `hlint` suggestions!

Thanks for everything, @petertseng!

```
$ hlint --version
HLint v1.9.37, (C) Neil Mitchell 2006-2016
j
$ hlint exercises
No hints (5 ignored)
```
